# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 902ea73fecac25325d199e048e136710700612b03d737cb171c0d2242c59bbea751bca6c8ee59a4d86531eb7d35f2916ffa51854ec437e5f126fde3ed20fa645

test:
  secret_key_base: 3841e4b45d85eca8043c80755ca359b8831d420fab558fbdcb41669560f3805e03270730661051f0fa4d721bc5c398dd53294f4ec7d257557dbda11d7728791f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
